const productsBySerial_v1 = `SELECT 
A.LOTE SERIAL,
A.ARTICULO,
B.T$DSCA DESCRIPCION, 
A.COMPRESOR SERIAL_COMPRESOR, 
A.ORDEN,
A.DOCUMENTO DOC_SALIDA,
D.T$NAMA DISTRIBUIDOR, 
(C.T$CDAT-0.209) FECHA_ENVIO, 
A.ALMACEN, A.CRFECHA 
FROM BAAN.TCHAPR018120 A, 
BAAN.TTCIBD001120 B, 
BAAN.TWHINH430120 C, 
BAAN.TTCCOM100120 D
WHERE COALESCE(RTRIM(LTRIM(B.T$ITEM)), B.T$ITEM) = COALESCE(RTRIM(LTRIM(A.ARTICULO)), B.T$ITEM)
AND A.DOCUMENTO=C.T$SHPM
AND A.TIPO=2
AND C.T$STCO=D.T$BPID
AND A.LOTE = :serialCode`;

const productsBySerial_v2 = `SELECT 
A.LOTE SERIAL,
A.ARTICULO,
B.T$DSCA DESCRIPCION_PROD, 
A.COMPRESOR SERIAL_COMPRESOR, 
A.ORDEN,
A.DOCUMENTO SP_SALIDA,
(C.T$CDAT-0.209) FECHA_ENVIO,
A.ALMACEN, 
F.T$NAMA DISTRIBUIDOR
FROM 
BAAN.TCHAPR018120 A
LEFT JOIN BAAN.TTCIBD001120 B ON LTRIM(RTRIM(A.ARTICULO))=LTRIM(RTRIM(B.T$ITEM))
LEFT JOIN BAAN.TWHINH430120 C ON LTRIM(RTRIM(A.DOCUMENTO))=LTRIM(RTRIM(C.T$SHPM))
LEFT JOIN BAAN.TTCCOM100120 D ON LTRIM(RTRIM(C.T$STCO))=LTRIM(RTRIM(D.T$BPID))
LEFT JOIN BAAN.TTDSLS400120 E ON A.ORDEN=E.T$ORNO
LEFT JOIN BAAN.TTCLOC008120 F ON E.T$OFBP = F.T$BPID
WHERE A.TIPO=2 
 AND A.ORIGEN=1
 AND A.LOTE = :serialCode`;

const asociatedProducts_v1 = `Select * From baan.tchapr008120
where Lote = :serialCode
    and ARTICULO = :skuCode`

const asociatedProducts_v2 = `Select * From BAAN.TCHAPR018120
where Lote = :serialCode
    and ARTICULO = :skuCode`

module.exports = { productsBySerial: productsBySerial_v2, asociatedProducts: asociatedProducts_v2 }