const productsBySerial = `SELECT 
A.LOTE SERIAL,
A.ARTICULO,
B.T$DSCA DESCRIPCION, 
A.COMPRESOR SERIAL_COMPRESOR, 
A.ORDEN,
A.DOCUMENTO DOC_SALIDA,
D.T$NAMA DISTRIBUIDOR, 
(C.T$CDAT-0.209) FECHA_ENVIO, 
A.ALMACEN, A.CRFECHA 
FROM BAAN.TCHAPR018120 A, 
BAAN.TTCIBD001120 B, 
BAAN.TWHINH430120 C, 
BAAN.TTCCOM100120 D
WHERE COALESCE(RTRIM(LTRIM(B.T$ITEM)), B.T$ITEM) = COALESCE(RTRIM(LTRIM(A.ARTICULO)), B.T$ITEM)
AND A.DOCUMENTO=C.T$SHPM
AND A.TIPO=2
AND C.T$STCO=D.T$BPID
AND A.LOTE = :serialCode`;

const asociatedProducts = `Select * From baan.tchapr008120
where Lote = :serialCode
    and ARTICULO = :skuCode`

module.exports = { productsBySerial, asociatedProducts }